src/main/java/com/woowacourse/matzip/domain/campus/Campus.java, src/main/java/com/woowacourse/matzip/domain/category/Category.java, src/main/java/com/woowacourse/matzip/domain/restaurant/Restaurant.java, src/main/java/com/woowacourse/matzip/domain/restaurant/RestaurantRepository.java, src/main/java/com/woowacourse/matzip/domain/review/Review.java, src/main/java/com/woowacourse/matzip/domain/review/ReviewRepository.java
- Restaurant entity 미구현
- Review entity 미구현
- Restaurant entity 구현
- Review entity 구현
- Restaurant와 Review는 id 값을 통한 간접 참조
- `@Column`에 실제 DB의 컬럼 명 매핑 `@Column(name = "restaurant_id")`
`Restaurant`의 `distance` 필드와 `Review`의 `score` 의 타입을 현재는 wrapper 타입으로 지정해 두었습니다.(`Long`, `Integer`) 이 부분에 대해서, 어차피 `(nullable = false)` 적용되어 있으니 primitive 타입을 쓰는 것이 맞을 지 의견을 내 주시면 감사하겠습니다.
=> feat: 식당, 리뷰 entity 구현

src/main/java/com/woowacourse/auth/application/JwtTokenProvider.java, src/main/java/com/woowacourse/auth/config/AuthConfig.java, src/main/java/com/woowacourse/auth/exception/AuthenticationContextException.java, src/main/java/com/woowacourse/auth/exception/InvalidTokenException.java, src/main/java/com/woowacourse/auth/exception/TokenNotFoundException.java, src/main/java/com/woowacourse/auth/presentation/AuthenticationArgumentResolver.java, src/main/java/com/woowacourse/auth/presentation/AuthenticationContext.java, src/main/java/com/woowacourse/auth/presentation/LoginInterceptor.java, src/main/java/com/woowacourse/auth/support/AuthenticationPrincipal.java, src/test/java/com/woowacourse/auth/application/JwtTokenProviderTest.java, src/test/java/com/woowacourse/document/Documentation.java
- 로그인 로직 처리를 비즈니스 로직에서 실행한다.
- 로그인 인터셉터를 구현한다.
- AuthContext를 생성한다.
- ArgumentResolver로 **githunId**값을 반환받는다.
인터셉터에 pattern 등록해서 사용하시면 됩니다.
Token의 Subject는 githubId입니다. 이 값 기반으로 Member정보를 찾아오면 됩니다.
에러관련해서, InternalException과 BadRequestException 등 RuntimeException을 상속받는 클래스를 만들어 이를 기준으로 예외를 구분하면 어떨까합니다. 혹은 에러 코드와 에러 메시지를 보관하는 enum 클래스를 만들어도 되구요.. 예외 핸들링 관련해서 이야기를 더 나눠봐야 할 것 같아요
=> feat: 로그인 관심사 분리

src/main/java/com/woowacourse/matzip/application/RestaurantService.java, src/main/java/com/woowacourse/matzip/application/response/RestaurantResponse.java, src/main/java/com/woowacourse/matzip/application/response/RestaurantTitleResponse.java, src/main/java/com/woowacourse/matzip/application/response/ReviewResponse.java, src/main/java/com/woowacourse/matzip/domain/restaurant/Restaurant.java, src/main/java/com/woowacourse/matzip/domain/review/Review.java, src/main/java/com/woowacourse/matzip/domain/review/ReviewRepository.java, src/main/java/com/woowacourse/matzip/presentation/RestaurantController.java, src/main/java/com/woowacourse/matzip/presentation/request/ReviewCreateRequest.java, src/main/resources/schema.sql, src/main/resources/static/index.html, src/test/java/com/woowacourse/document/DocumentationFixture.java, src/test/java/com/woowacourse/matzip/application/RestaurantServiceTest.java, src/test/java/com/woowacourse/matzip/domain/restaurant/RestaurantRepositoryTest.java, src/test/java/com/woowacourse/matzip/domain/review/ReviewRepositoryTest.java, src/test/java/com/woowacourse/matzip/domain/review/ReviewTest.java
- 식당 목록 조회 시 별점 정보를 가져오지 않음
- 별점 값 변수명 변경 필요(현재 score, rating으로 변경하기로 합의)
- 식당 목록 조회 시 너무 많은 정보를 담아줌
- 식당 목록 조회 시 평균 별점 정보를 가져오는 기능 구현
- 별점 값의 변수명을 score -> rating으로 변경
- 식당 목록 조회 시 필요한 정보만 반환하는 dto를 추가
=> feat: 식당 목록 조회 시 평균 별점을 함께 조회하는 기능 구현

src/main/java/com/woowacourse/matzip/application/RestaurantService.java, src/main/java/com/woowacourse/matzip/application/ReviewService.java, src/main/java/com/woowacourse/matzip/application/response/RestaurantTitlesResponse.java, src/main/java/com/woowacourse/matzip/application/response/ReviewsResponse.java, src/main/java/com/woowacourse/matzip/domain/restaurant/RestaurantRepository.java, src/main/java/com/woowacourse/matzip/domain/review/ReviewRepository.java, src/main/java/com/woowacourse/matzip/presentation/RestaurantController.java, src/main/java/com/woowacourse/matzip/presentation/ReviewController.java, src/test/java/com/woowacourse/acceptance/ReviewAcceptanceTest.java, src/test/java/com/woowacourse/document/DocumentationFixture.java, src/test/java/com/woowacourse/matzip/application/RestaurantServiceTest.java, src/test/java/com/woowacourse/matzip/application/ReviewServiceTest.java, src/test/java/com/woowacourse/matzip/domain/restaurant/RestaurantRepositoryTest.java, src/test/java/com/woowacourse/matzip/domain/review/ReviewRepositoryTest.java
- 무한 페이징을 위한 boolean `hasNext` 값 미구현
- Repository에서 식당 목록 반환 시 Slice로 반환하도록 구현 완료
- Service에서 hasNext값이 들어 있는 dto 반환하도록 구현 완료
=> feat: 식당 목록, 리뷰 목록 응답 시 무한 페이징을 위한 hasNext 값을 함께 응답하는 기능 구현

src/docs/asciidoc/restaurant.adoc, src/main/java/com/woowacourse/matzip/application/RestaurantService.java, src/main/java/com/woowacourse/matzip/domain/restaurant/RestaurantRepository.java, src/main/java/com/woowacourse/matzip/presentation/RestaurantController.java, src/test/java/com/woowacourse/acceptance/RestaurantAcceptanceTest.java, src/test/java/com/woowacourse/document/DocumentationFixture.java, src/test/java/com/woowacourse/document/RestaurantDocumentation.java, src/test/java/com/woowacourse/matzip/application/RestaurantServiceTest.java, src/test/java/com/woowacourse/matzip/domain/restaurant/RestaurantRepositoryTest.java, src/test/resources/data.sql
- 식당 검색 api 미구현
- 식당 검색 쿼리 미구현
- `findPageByCampusIdAndNameContainingIgnoreCase()` 식당 검색 쿼리 추가
- `GET /campuses/{campusId}/restaurants/search` name, page, size param api 추가
=> feat: 식당 검색기능 추가

src/docs/asciidoc/restaurant.adoc, src/main/java/com/woowacourse/matzip/application/RestaurantService.java, src/main/java/com/woowacourse/matzip/application/response/RestaurantResponse.java, src/main/java/com/woowacourse/matzip/application/response/RestaurantTitleResponse.java, src/test/java/com/woowacourse/document/DocumentationFixture.java, src/test/java/com/woowacourse/document/RestaurantDocumentation.java, src/test/java/com/woowacourse/document/ReviewDocumentation.java, src/test/java/com/woowacourse/matzip/application/RestaurantServiceTest.java
- 식당 상세 조회 시 평균 별점 정보 조회 미구현
- 가나다순 식당 조회 Service 테스트 미구현
- 별점순 / 가나다순 식당 조회 documentation 미구현
- 식당 상세 조회 시 평균 별점 정보를 담도록 구현 완료
- 가나다순 식당 조회 Service 테스트 구현 완료
- 별점순 / 가나다순 식당 조회 docs 구현 완료
=> feat: 식당 상세 목록 조회 시 평균 별점도 함께 조회하는 기능 구현, 누락된 테스트 추가

src/main/java/com/woowacourse/matzip/domain/campus/Campus.java, src/main/java/com/woowacourse/matzip/domain/category/Category.java, src/main/java/com/woowacourse/matzip/domain/restaurant/Restaurant.java, src/main/java/com/woowacourse/matzip/domain/review/Review.java, src/main/java/com/woowacourse/matzip/exception/InvalidLengthException.java, src/main/java/com/woowacourse/matzip/presentation/ReviewController.java, src/main/java/com/woowacourse/matzip/presentation/request/ReviewCreateRequest.java, src/main/java/com/woowacourse/matzip/support/LengthValidator.java, src/main/java/com/woowacourse/support/exception/ErrorResponse.java, src/main/java/com/woowacourse/support/exception/GlobalControllerAdvice.java, src/test/java/com/woowacourse/acceptance/ReviewAcceptanceTest.java, src/test/java/com/woowacourse/matzip/domain/campus/CampusTest.java, src/test/java/com/woowacourse/matzip/domain/category/CategoryTest.java, src/test/java/com/woowacourse/matzip/domain/restaurant/RestaurantRepositoryTest.java, src/test/java/com/woowacourse/matzip/domain/restaurant/RestaurantTest.java, src/test/java/com/woowacourse/matzip/domain/review/ReviewTest.java, src/test/java/com/woowacourse/matzip/support/LengthValidatorTest.java
- input값에 대한 도메인 객체들 길이 제한이 존재하지 않음
- ReviewCreateRequest의 null 제한 누락
- 스키마 정보와 동일한 길이 validation 추가
- `matzip.support.LengthValidator.java` util 클래스 추가
- max, min-max 길이 제한 예외처리가 공통적으로 들어가는 내용이 많아 묶어서 처리하기 위한 용도
- `InvalidLengthException`을 반환하고 있음.
- _해당 util 클래스가 필요한가 불필요한가에 대한 논의필요 (오버프로그래밍이라고 생각하고 있기는 함)_
- spring-validation 추가로 앞단에서 처리 추가
- `MethodArgumentNotValidException`에 대한 예외처리진행중 -> 해당 exception에서 message가 2개 이상이 발생해도 현재는 list가 아닌 String으로 반환하고 있기 때문에 가장 먼저 나온 에러를 `get(0)`하여 하나의 메시지만 반환하도록 처리중
=> feat: 도메인별 validation 로직을 추가한다.

src/main/java/com/woowacourse/matzip/domain/review/ReviewRepository.java
- #45 
- `@EntityGraph(attributePaths = {"member"}, type = EntityGraphType.FETCH)` 추가로 fetch join 제한
- `Member`에 대한 join 문 확인
```mysql
Hibernate: 
select
review0_.id as id1_4_0_,
member1_.id as id1_2_1_,
review0_.content as content2_4_0_,
review0_.member_id as member_i6_4_0_,
review0_.menu as menu3_4_0_,
review0_.rating as rating4_4_0_,
review0_.restaurant_id as restaura5_4_0_,
member1_.github_id as github_i2_2_1_,
member1_.profile_image as profile_3_2_1_,
member1_.username as username4_2_1_ 
from
review review0_ 
left outer join
member member1_ 
on review0_.member_id=member1_.id 
where
review0_.restaurant_id=? 
order by
review0_.id desc limit ?
```
=> feat: review paging 조회 시 member fetch join 추가

src/main/java/com/woowacourse/MatzipApplication.java, src/main/java/com/woowacourse/matzip/domain/review/Review.java, src/main/java/com/woowacourse/support/config/JpaConfig.java, src/test/java/com/woowacourse/matzip/domain/review/ReviewRepositoryTest.java, src/test/resources/schema.sql
- 리뷰 생성일자 누락
- application 실행 시 timezone asia/seoul 변경
- `@EnableJpaAuditing` 용 configuration 추가
- 리뷰 내 created_at 필드 추가
- created_at 정상 저장되는지 확인 테스트 추가
=> feat: 리뷰 생성 시 생성 일자 추가

build.gradle
- REST Docs 결과물인 `index.html`이 프로덕션 코드의 static에는 생기지만, 실제 JAR를 만들 때는 포함되지 않음.
- `createDocument` 작업 뒤 JAR 파일을 만드는 디렉토리에 복사하는 `copyDocument` 작업 추가
=> chore: createDocument 작업 뒤에 JAR 만드는 디렉토리로 옮기는 copyDocument 태스크 추가

src/main/java/com/woowacourse/auth/config/AuthConfig.java, src/main/java/com/woowacourse/auth/presentation/interceptor/LoginInterceptor.java, src/main/java/com/woowacourse/auth/presentation/interceptor/PathContainer.java, src/main/java/com/woowacourse/auth/presentation/interceptor/PathMatcherInterceptor.java, src/main/java/com/woowacourse/auth/presentation/interceptor/PathMethod.java, src/main/java/com/woowacourse/auth/presentation/interceptor/RequestPathPattern.java, src/test/java/com/woowacourse/auth/presentation/interceptor/PathContainerTest.java, src/test/java/com/woowacourse/auth/presentation/interceptor/PathMethodTest.java, src/test/java/com/woowacourse/auth/presentation/interceptor/RequestPathPatternTest.java
- 이슈에 과거 상황을 적어두었습니다.
```java
@Override
public void addInterceptors(final InterceptorRegistry registry) {
registry.addInterceptor(loginInterceptor());
}
private HandlerInterceptor loginInterceptor() {
return new PathMatcherInterceptor(loginInterceptor)
.excludePathPattern("/**", PathMethod.OPTIONS) // 검사하고 싶지 않은 path, pattern을 exclude합니다.
.includePathPattern("/api/restaurants/*/reviews", PathMethod.POST); // 검사하고 싶은 경우엔 include 합니다.
}
```
1. enum 메서드 상속
PathMethod.ANY에 대한 더 좋은 의견이 있다면 말해주세요.
```java
public enum PathMethod {
GET,
POST,
PUT,
PATCH,
DELETE,
OPTIONS,
TRACE,
HEAD,
ANY {
@Override
public boolean matches(final String method) {
return Arrays.stream(values())
.filter(value -> !value.equals(ANY))
.anyMatch(value -> value.name().equalsIgnoreCase(method));
}
};
public boolean …
```
=> refactor: 인터셉터 프록시패턴 적용

app-external-api/src/docs/asciidoc/review.adoc, app-external-api/src/main/java/com/woowacourse/auth/config/AuthConfig.java, app-external-api/src/main/java/com/woowacourse/matzip/application/ReviewService.java, app-external-api/src/main/java/com/woowacourse/matzip/presentation/ReviewController.java, app-external-api/src/main/java/com/woowacourse/matzip/presentation/request/ReviewUpdateRequest.java, app-external-api/src/main/java/com/woowacourse/support/exception/GlobalControllerAdvice.java, app-external-api/src/test/java/com/woowacourse/acceptance/ReviewAcceptanceTest.java, app-external-api/src/test/java/com/woowacourse/acceptance/support/RestAssuredRequest.java, app-external-api/src/test/java/com/woowacourse/document/ReviewDocumentation.java, app-external-api/src/test/java/com/woowacourse/matzip/application/ReviewServiceTest.java, common/src/main/java/com/woowacourse/matzip/exception/ForbiddenException.java, common/src/main/java/com/woowacourse/matzip/exception/ReviewNotFoundException.java, core/src/main/java/com/woowacourse/matzip/domain/review/Review.java, core/src/test/java/com/woowacourse/matzip/domain/review/ReviewTest.java
- 리뷰 수정, 삭제 api가 없음
`PUT /api/restaurants/{restaurantId}/reviews/{reviewId}`
content: String
rating: NUMBER
menu: String
`DELETE /api/restaurants/{restaurantId}/reviews/{reviewId}`
현재 deleteReview 코드가 절차적으로 작성되어 있습니다.
삭제라는 도메인 로직을 응용 레이어에서 갖고 있어요. 이런 경우 저는 도메인에 delete 메서드를 만들고 delete를 실행할 수 있는 [도메인 서비스](https://www.manty.co.kr/bbs/detail/develop?id=146) 를 만들어 사용하는 편입니다. 하지만 현재 멀티 모듈 구조상 repository를 api 모듈에서 참조하면 도메인에 해당 도메인 서비스를 넣을 수 없고(의존성이 api -> core 이기 때문) 도메인 서비스가 코어에 있을 경우 repository를 참조할 수 가 없습니다.
따라서 핵심이 되는 Repository는 core로 이동하여 도메인 서비스를 만들 수 있도록 하면 응용 계층에서의 도메인 지식을 제거할 수 있을 것 같습니다.
=> feat: 리뷰 수정, 삭제 api를 구현한다.

common/src/main/java/com/woowacourse/matzip/exception/AlreadyRegisteredException.java, common/src/main/java/com/woowacourse/matzip/exception/ForbiddenException.java, core/src/main/java/com/woowacourse/matzip/domain/member/Member.java, core/src/main/java/com/woowacourse/matzip/domain/restaurant/RestaurantRequest.java, core/src/test/java/com/woowacourse/matzip/domain/restaurant/RestaurantRequestTest.java
- 식당 추가 요청 도메인이 존재하지 않음
- 식당 추가 요청 도메인 구현
- 카테고리 id, 캠퍼스 id, 멤버(작성자), 등록여부를 가짐
- 수정 시에는 반드시 작성자 검증을 하도록 구현
- 등록 시(요청 생성이 아님, 요청을 바탕으로 실제 식당을 등록할 때 `registered` 값이 변경되는 것을 의미)에는 admin이 등록할 것이므로 작성자 검증 로직이 포함되어 있지 않음
- admin에서 구현할 때 관리자 검증을 따로 하면 될 듯
- 기존에 존재하던 `Member` 클래스가 지연 로딩으로 로딩되는데, equals가 프록시를 고려하지 않아서 해당 부분 수정
=> feat: 식당 추가 요청 도메인을 구현한다

app-internal-api/build.gradle, app-internal-api/src/main/java/com/woowacourse/matzip/MatzipApplication.java, app-internal-api/src/main/java/com/woowacourse/matzip/application/AdminMemberService.java, app-internal-api/src/main/java/com/woowacourse/matzip/application/AdminRestaurantService.java, app-internal-api/src/main/java/com/woowacourse/matzip/application/AdminReviewService.java, app-internal-api/src/main/java/com/woowacourse/matzip/application/response/RestaurantResponse.java, app-internal-api/src/main/java/com/woowacourse/matzip/application/response/ReviewResponse.java, app-internal-api/src/main/java/com/woowacourse/matzip/repository/CampusRepository.java, app-internal-api/src/main/java/com/woowacourse/matzip/repository/CategoryRepository.java, app-internal-api/src/main/java/com/woowacourse/matzip/repository/MemberRepository.java, app-internal-api/src/main/java/com/woowacourse/matzip/repository/RestaurantRepository.java, app-internal-api/src/main/java/com/woowacourse/matzip/repository/ReviewRepository.java, app-internal-api/src/main/java/com/woowacourse/matzip/ui/MainView.java, app-internal-api/src/main/java/com/woowacourse/matzip/ui/SideNavbarLayout.java, app-internal-api/src/main/java/com/woowacourse/matzip/ui/member/MemberDetailForm.java, app-internal-api/src/main/java/com/woowacourse/matzip/ui/member/MemberListView.java, app-internal-api/src/main/java/com/woowacourse/matzip/ui/restaurant/RestaurantListView.java, app-internal-api/src/main/java/com/woowacourse/matzip/ui/review/ReviewListView.java, app-internal-api/src/main/resources/application.yml, app-internal-api/src/main/resources/data.sql, app-internal-api/src/main/resources/schema.sql, common/src/main/java/com/woowacourse/matzip/exception/CategoryNotFoundException.java, settings.gradle
- clone -> application 실행 -> 하단 npm install 탭나오면 클릭
- 아래와 같은 route로 페이지 이동이 진행된다면 정상작동입니다.
- live reload : https://youngkyonyou.github.io/springboot/2021/07/07/springboot-post16.html
- 관련해서 생서된 어드민 프론트페이지도 과연 repo에 추가해야하나 싶네요. restdocs도 지금 update계속 하고 있긴한데 둘다 지금 삭제하고 배포시에만 확인할거라면 굳이 git에 올리지 않아도 생각이 듭니다. 관련해서 의견있다면 이야기부탁드려요.
- `app-internal-api` 모듈 추가
- vaadin 구축을 위한 build script 설정
- 유저, 음식점, 리뷰 전체 조회기능 추가
- 어드민을 위한 모듈을 추가하였습니다.
- 이전에 이야기한대로 repository에 대한 부분은 전체 구현을 마무리한 뒤 core 모듈로 통합할 예정입니다.
- 설정관련해서 이야기할 부분이 있는데, application은 현재 두가지로 `external`과 `internal`이 두개가 있습니다. 이 둘이 중복되는 설정값(ex spring-boot-web)이 많아 공통적으로 나중에 처리해두어야할 것 같네요.
- 기본설정만 해두었습니다.
- vaadin docs에서 제공되는 default 설정값만 추가하였으며 spring-boot starter에서도 vaadin에 대한 추가를 진행해주어 거기서 크게 수정없이 된 점 참고 부탁드립니다. …
=> vaadin을 통한 admin 페이지 구현을 진행한다.

matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/response/RestaurantDemandResponse.java
- RestaurantDemand 생성 시 member.githubId가 주입됨
- member.githubId 대신 member.username을 넣도록 수정
=> fix: 식당 추가 요청 조회 응답에 github id가 아닌 username을 노출

.gitmodules, README.md, matzip-app-external-api/src/main/resources/application.yml
- production 환경의 application.yml 파일을 서버에서 관리하여 prod 설정을 local에서 알 수 없다.
- production 환경의 application.yml 파일을 서브 모듈로 관리한다.
=> feat: prod application.yml submodule로 분리

.github/workflows/sonar-cloud-analysis-build.yml, build.gradle, gradle/wrapper/gradle-wrapper.properties, matzip-app-external-api/build.gradle
- java 11과 springboot 2.7.5 사용
- java 17부터 순착적으로 적용, ~~springboot 3.2.2로 업그레이드~~
- gradle 버전 상향 ~~및 restassured, jakarta 등의 의존성 수정~~
dto class를 record로 수정하는 등의 변경이 필요할까요?
~~빠른 시일내에 해결해보겠습니다~~
=> chore: jdk 17로 업데이트

build.gradle, matzip-app-external-api/build.gradle
- 3.0.13 GA버전 사용
- api 명세 페이지 접속시 404 발생
- 3.1.x 버전대 GA 버전인 3.1.8 적용
- asciidoctor 버전 업그레이드 및 gradle 설정 변경
=> springboot 3.1.8 적용 및 asciidoctor 설정 변경

matzip-app-external-api/build.gradle, matzip-app-external-api/src/docs/asciidoc/index.adoc
- 이전 버전의 asciidoc 경로를 사용하고 있어서 index.html이 옮겨지지 않아 404 발생
- 변경된 bulid/docs/asciidoc 경로로 수정해서 정상적으로 static 파일로 옮겨지는 것 확인
=> chore: asciidoc gradle 설정 변경

build.gradle, matzip-app-external-api/build.gradle
- springboot 3.1.8 버전 사용
- springboot ga 버전인 3.2.3 으로 업그레이드
- 모니터링 구축을 위한 actuator 의존성 추가
=> chore: springboot 3.2.3 및 actuator 의존성 추가

matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/BookmarkService.java, matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/RestaurantService.java, matzip-app-external-api/src/main/java/com/woowacourse/matzip/infrastructure/restaurant/RestaurantFindQueryFactory.java, matzip-app-external-api/src/main/java/com/woowacourse/matzip/infrastructure/restaurant/RestaurantQueryRepository.java, matzip-app-external-api/src/main/java/com/woowacourse/matzip/presentation/BookmarkController.java, matzip-app-external-api/src/main/java/com/woowacourse/matzip/presentation/RestaurantController.java, matzip-app-external-api/src/test/java/com/woowacourse/matzip/application/RestaurantServiceTest.java, matzip-app-external-api/src/test/java/com/woowacourse/matzip/infrastructure/restaurant/RestaurantQueryRepositoryTest.java, matzip-core/src/main/java/com/woowacourse/matzip/domain/restaurant/Restaurant.java, matzip-core/src/testFixtures/java/com/woowacourse/matzip/TestFixtureCreateUtil.java
- `별점 순` 과 `가나다 순` 정렬만으로 원하는 조건을 맛집을 파악하기 힘들다.
> 거리 순 정렬
- 기존의 거리 정보 데이터를 활용하여거리 순 오름차순 정렬 기능을 추가하여 가장 가까운 맛집을 빠르게 찾을 수 있도록 돕는다.
- 거리가 같을 경우 이름 기준으로 오름차순 정렬한다.
> 좋아요 순(찜 순) 정렬
- 좋아요 순 내림차순 정렬을 추가하여 "개인 소장 찐 맛집" 순서대로 볼 수 있도록 돕는다.
- 좋아요 수(찜 수)가 같을 경우 이름 기준으로 오름차순 정렬한다.
=> feat: 식당 검색 필터링 옵션에 거리 가까운 순과 좋아요 순을 추가한다.

matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/RestaurantService.java, matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/response/RestaurantResponse.java, matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/response/RestaurantTitleResponse.java, matzip-app-external-api/src/test/java/com/woowacourse/document/DocumentationFixture.java, matzip-app-external-api/src/test/java/com/woowacourse/matzip/application/RestaurantServiceTest.java, matzip-core/src/main/java/com/woowacourse/matzip/domain/bookmark/BookmarkRepository.java, matzip-core/src/testFixtures/java/com/woowacourse/matzip/TestFixtureCreateUtil.java
- 사용자들이 어떤 음식점을 맛집으로 생각하는지 직관적으로 알기 어려움
- 식당을 조회할 때 북마크 수량을 함께 조회
=> feat: 식당 조회시 북마크 수량 조회 기능
